Feature
sayonara20xx/react_hacker_news pull request #1
Opened 2022-07-14 09:41 UTC by sayonara20xx

Инит коммит был уже с написанным кодом, надеюсь что комментировать можно не только изменения, хотя там tsx файлы все как новые

2022-07-14 09:48 UTC, sayonara20xx commented
https://codesandbox.io/s/funny-bartik-wdbbve - sandbox feature

2022-07-18 10:59 UTC, Stilwuc requested changes
Вообщем неплохо.
Пару важных моментов поправь и вообще хорошо будет :)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +          return json.slice(0, 100);
Новости не отсортированны по дате
![image](https://user-images.githubusercontent.com/44724024/179467510-5f96f32f-b709-499b-80f9-2510dadcdd76.png)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsInfo/Comment/Comment.tsx
> +      <p onClick={commClicked}>{returnText()}</p>
Не рендерится `html` верстка в контенте коммента
![image](https://user-images.githubusercontent.com/44724024/179468051-03989b3f-3867-44d8-b1b4-cc1ceb48b857.png)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +        <Route path="/info" element={<NewsInfo data={selectedNew} />} />
Использовать `route Data` норм, но не всегда)
Например тут, зайдя на роут новости все ок, пока не обновишь страницу и не получишь вот это 
![image](https://user-images.githubusercontent.com/44724024/179468299-459ed33c-7d2f-4c4d-8136-40cd7d942f9d.png)
Поэтому `routeData` больше для каких то не `persist` вещей. Поищи тут другое решение как можно хранить и передавать информацию о выбранной новости

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +  const refreshButtonClick = (): void => {
`refresh button` сделан не совсем удобно.
При нажатии на него весь экран белым становится на секунду. Не очень `UX`.
Было бы классно если бы ты только ререндерил сами итемы

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsInfo/NewsInfo.tsx
> +        <TitleText>{"Descendants: " + props.data.descendants}</TitleText>
Не самое очевидное название для количества комментариев)
Мб по проще и дефолт `Comments` / `CommentsCount`?

2022-07-18 10:59 UTC, Stilwuc commented on package.json
> +    "eslint": "^8.19.0",
`eslint`, `prettier`, `testing utils` должны быть `devDependencies`, так как эти пакеты не будут использоваться в проде(чисто `dev ex`)

2022-07-18 10:59 UTC, Stilwuc commented on public/index.html
> +            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vm
Лучше `boostrap` тоже через `npm` подрубать, а то не камельфо когда что-то через `cdn'ку`, а что то через `npm`.
Да и вообщем то `npm` приоритетней для юза

2022-07-18 10:59 UTC, Stilwuc commented on src/App.tsx
> +const App: () => JSX.Element = () => {
Лучше юзать type `alias` из `"react"` - `FC`.
Поддерживает передачу пропов и тд, и лучше привыкать юзать его, в `react 18` так точно)

2022-07-18 10:59 UTC, Stilwuc commented on src/App.tsx
>      <div className="App">
Не увидел стилей на этот класс. Можно выпилить вместе с дивом, лишних элементов в доме не будем создавать)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsInfo/NewsInfo.tsx
> +import React, { useEffect, useState } from "react";
Так как ты переписал модули на styled, то структура типа - `NewsSummary/NewsSummary.tsx` уже излишне, достаточно просто хранить `NewsSummary.tsx`.
Просто не стоит делать много вложенных папок, потом придется постоянно их раскрывать при поиске компонента)
Если что, группировать какую то логику имеет смысл, но тут пока нет

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/HackerNews.tsx
> +      <div>
Тут точно лишний `div`. Без надобности доп вложенность `DOM` не делаем

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +      <Routes>
По факту у тебя `MainPage` (текущий компонент) не является таковым, так как в нем создаются два других роута.
`Routes` предлагаю выкинуть повыше в `HackerNews`, и там объявить два роута `MainPage` и `InfoPage`.
\+ это пофиксит проблему условного рендеринга `Routes`, это не совсем хорошая практика рендерить список роутов по условию которое часто меняется, тем более тебе здесь это точно не нужно

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +export interface response {
`interface` и `type` в `PascalCase`
Ну и возможно название можно менее абстрактней сделать)
```suggestion
export interface NewsItem {
```

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +  kids: Array<number>;
Лучше short синтаксис типизации массива юзать, легче читать)
```suggestion
  kids: number[];
```

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +  const [news, setNews] = useState<Array<response>>(() => {
Необязательно тут юзать `getter` для начального значения, проще будет обычной иницилизацией
```suggestion
  const [news, setNews] = useState<Array<response>>([]);
```

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +      id: -1,
Не стоит делать empty объект под интерфейс, boilerplate код плодится. 
Лучше сделай что стейт может быть как `response` так и `null`

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +    setInterval(() => {
Сейчас у тебя этот `setInterval` не чистится, и будет работать даже когда уйдем со страницы.
Обычно это ведет к утечке памяти, поэтому надо за собой все это подчищать перед уходом

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +        setNewsIds(() => {
Тут `setter` тоже проще обычный юзать, так как все равно аргумент текущего стейта не юзаешь
```suggestion
        setNewsIds(json.slice(0, 100));
```

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +import React, { useEffect, useState } from "react";
Еще, не заюзал `state management`, лучше подумать что в него выкинуть и заюзать. Советую `createContext`, попроще)
![image](https://user-images.githubusercontent.com/44724024/179488622-467d5a3e-d33c-4c11-9964-bfce56441955.png)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +  const url =
Названия не делай слишком абстрактные. Пример смотрю я такой `fetch(url)` и сейчас по названию переменной я 0 идей куда запрос пойдет. В данном случае например можно назвать `fetchTopStoriesUrl`
![image](https://user-images.githubusercontent.com/44724024/179489898-bb86f449-ed08-43ca-8e88-db75edfc85f8.png)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +      if (window.location.pathname === "/") {
От этой прикольной проверки уйдем, если разделить страницы на разные компоненты

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +          setNews((prevState) => {
Интересное решение, у тебя 100 раз вызывается `setState`. По идее `batching` сработает и кучу ререндеров не будет лишних, но все же мне кажется лучше один раз засетить 100 элементов чем 100 раз один)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +      // Костыль: у веб апи нельзя определить кол-во постов, получаем 500, выкидываю 400
Не надо дублировать одну и ту же функцию `fetch` два раза. Вынеси получение `id` новостей в отдельную функцию и вызывай её тут и в `setInterval`

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +  const [newsIds, setNewsIds] = useState(() => {
Типизации нету. Сейчас это `never[]`
```suggestion
  const [newsIds, setNewsIds] = useState<number[]>(() => {
```

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +    return null;
Чтобы не было больших вложенных блоков if, лучше юзать ранний выход из функции, в твое примере это было бы так
```
if (!newsIds.length) return null;

return (
      <Routes>
....
```

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/MainPage.tsx
> +                  ></NewsSummary>
Юзай самозакрывающие теги если children не нужен
```suggestion
                  />
```

2022-07-18 10:59 UTC, Stilwuc commented on tsconfig.json
> +    // "incremental": true,                              /* Save .tsbuildinfo files to allow for incremental compilation of projects. */
в json комментов нету, возможно tsconfig пофиг, но лучше выпилить, тем более что комменты не особо полезные, это всегда можно в доке посмотреть)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsSummary/NewsSummary.tsx
> +const NewsSummary: (arg0: props) => JSX.Element = (props) => {
Такая типизация компонента не очень, через FC здесь было бы так
```suggestion
const NewsSummary: FC<props> (props) => {
```
P. S. Не забудь кейс интерфейса поправить

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsSummary/NewsSummary.tsx
> +export interface props {
Так как ты этот интерфейс еще экспортишь, надо точно норм название для него. А то прикинь у тебя будет 10 таких интерфейсов абстрактных из разных компонентов экспортится, не удобно.
Обычно название интерфейса пропов это "Название компонента + Props", поэтому тут получится `NewsSummaryProps`

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsSummary/NewsSummary.tsx
> +  data: {
Ты этот интерфейс уже объявлял, лучше переиспользовать его

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsSummary/NewsSummary.tsx
> +      <p>{"Rating: " + props.data.score + ", author: " + props.data.by}</p>
Конкатинацию строк лучше через интерполяцию делать. Лучше читается
```suggestion
      <p>{`Rating: ${props.data.score}, author: ${props.data.by}`}</p>
```

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsSummary/NewsSummary.tsx
> +  let formattedDate: Date = new Date(props.data.time * 1000);
Почему `let`, если значение не меняешь, юзай `const`

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsSummary/NewsSummary.tsx
> +  let formattedDate: Date = new Date(props.data.time * 1000);
Ты кстати не форматнул дату, типо в текущем варианте он просто Date.toString делает, и получается не совсем красиво. Лучше бы в более читаемом формате выводить)
![image](https://user-images.githubusercontent.com/44724024/179495365-2b816f4d-247f-4031-b0f1-79f1062ea121.png)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsInfo/Comment/Comment.tsx
> +const NIcknameP = styled.p`
Странный кейс названия.
+ необязательно в конце постфиксом добавлять тип элемента(`P`), иногда достаточно просто `Nickname`

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsInfo/Comment/Comment.tsx
> +export interface CommProps {
Сокращения юзай обдуманно.
сокращения `comm` для comments неочевидно, а если не очевидно, то лучше и не сокращать.
Читаемость > длины названия

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsInfo/Comment/Comment.tsx
> +    if (isClicked && commInfo.kids && props.id && commInfo.kids.length > 0)
Вот такой баг славил на раскрытие дерева комментов
![image](https://user-images.githubusercontent.com/44724024/179496219-cd99054f-3923-49bd-99f1-e50ea9cfed3d.png)
Id = 32134691

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsInfo/Comment/Comment.tsx
> +      return commInfo.text + ". Click on text to watch reply(es).";
Чутка придирка, но неочевидно что на нажатие откроется тред комментов, так как слипается с текстом коммента
![image](https://user-images.githubusercontent.com/44724024/179496487-fbe3cf5e-2a73-4902-8806-68cf62da920f.png)

2022-07-18 10:59 UTC, Stilwuc commented on src/HackerNews/MainPage/NewsInfo/Comment/Comment.tsx
> +  const [isClicked, setIsClicked] = useState(() => false);
При обновлении комментов по времени(раз в минуту), сбрасывается все состояние открытых комментов, и скролимся в топ. Не удобно(

2022-07-18 11:12 UTC, crutch12 commented
С дизайном всё очень плохо, выкидывай все свои заготовки
и сажай на react-bootstrap или mui

2022-07-22 16:40 UTC, sayonara20xx commented
Вроде как все подправил, запилил новый дизайн, новости в виде бутстраповского грида, вся инфа в виде его же карточек, надеюсь так будет получше.

Обновление комментариев с сохранением вида развернутых пытался реализовать двумя способами: 
передавать им в пропсы их детей (не представил как обновлять чисто какой-то стейт дочерний и при этом все не перерендерить);
с помощью доп инфы в виде коллекции данных в контексте (объект, который обновляется каждый раз при изменении стейта isClicked в каждом коменте, соответственно каждый комментарий должен знать свое место в дереве, эту инфу можно внутри map сформировать и передавать так же через props, но я не смог нормально догнать как этот объект модифицировать, по сути надо было превратить массив в данных в последовательность ключей для обращения к этому объекту, но это как-то все громоздко)

Еще, интервалы я чистил только при использовании NavLink, не знаю, нужно ли еще как-то их отрабатывать. И насчет использования localStorage для хранения выбранной новости тоже не уверен, но с ним все работает.

2022-07-22 16:40 UTC, sayonara20xx commented
https://codesandbox.io/s/pensive-surf-t8l6iw - codesandbox

2022-07-26 12:46 UTC, Stilwuc requested changes

2022-07-26 12:46 UTC, Stilwuc commented on src/index.js
> +import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
При импорте либ обычно `node_modules` не надо, должно заресолвится само
```suggestion
import 'bootstrap/dist/css/bootstrap.min.css';
```

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/Comment.tsx
> +const HighlightedP = styled.p`
Аккуратно с `<p>`. Например сейчас у тебя есть вложенные параграфы в другие параграфы, а это html не корретно
![image](https://user-images.githubusercontent.com/44724024/180993193-2d7f8d0c-dd56-4682-82a7-110308bcabf4.png)

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/Comment.tsx
> +  const [commentKids, setCommentKids] = useState<number[] | null>(() => {
Не везде это поправил
![image](https://user-images.githubusercontent.com/44724024/180994003-20640268-ee9c-41a2-bd93-6a2b69945b31.png)

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/Comment.tsx
> +        {renderComments()}
Было бы неплохо если бы ты deleted комменты обрабатывал
![image](https://user-images.githubusercontent.com/44724024/180994228-da87c322-4a96-4791-9abe-aba54b8d7fd9.png)

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/Comment.tsx
> +        setCommentInfo(() => {
можешь просто ложить весь `response` в `setter`, даже если будет больше полей чем ожидает state все ок, до тех пор пока будут те обязательные поля

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/Comment.tsx
> +    let url = `https://hacker-news.firebaseio.com/v0/item/${props.id}.json?print=pretty`;
Ты делаешь два одинаковы запроса(#24) чтобы результат пополам поделить и положить в разные стейты, не оч.
Ты в одном запросе можешь сделать два сетера, да и вообще два стейта тут не зачем

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/SelectedNewStore.ts
> +  setSelectedNewCallback: (event: React.MouseEvent<HTMLAnchorElement>, obj: NewsDataResponse) => void;
Обычно наименование коллбэков с префиксом `on` идет, ты наверно видел такое в тех же `<button>` и тд.
Поэтому тут можно просто что то типо
```suggestion
  onSelectNews: (event: React.MouseEvent<HTMLAnchorElement>, obj: NewsDataResponse) => void;
```

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/MainPage.tsx
> +  const IntervalID: React.MutableRefObject<NodeJS.Timer | undefined> = useRef();
интересно что это в PascalCase хотя это обычная переменная)

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/MainPage.tsx
> +      setNewsIds(() => {
Тоже можно избавиться от второго стейта, просто здесь сразу выполни функцию фетча по новости по id
А то контролировать два стейта отвечающее за +- одно и то же сложней чем один)

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/MainPage.tsx
> +          if (tempArray.length === 100) {
Ты можешь заюзать `Promise.all` с масивом промисей получившихся через `map`, подождать когда они заресолвятся и после этого делать sort и сет.
А то хардкод длина массива = 100 значит элемент последний не кайф

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/MainPage.tsx
> +      <Row className={'justify-content-md-center mt-3'}>
```suggestion
      <Row className="justify-content-md-center mt-3">
```

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/NewsInfo.tsx
> +    selectedNew = localStorage.getItem('selectedNewObject');
мм, интересное решение, но я все равно могу сломать его)
1. Открыть в одной вкладке новость 1
2. Открыть в другой вкладке новость 2
3. Обновить вкладку с новостью 1
4. После обновления ты получишь новость 2
Так что надо по другому идти, небольшая подсказка - это делается через react-router

2022-07-26 12:46 UTC, Stilwuc commented on src/HackerNews/NewsInfo.tsx
> +  const refreshOnCLick = (): void => {
```suggestion
  const refreshOnClick = (): void => {
```

2022-08-02 23:49 UTC, crutch12 commented
Я вспомнил, что тебе нужно было сделать ещё опциональное задание
> Из опциональных, сделай:
> > Конфигурация сборки проекта в Docker image

2022-08-05 09:45 UTC, sayonara20xx commented
Все подправил

2022-08-05 12:46 UTC, Stilwuc requested changes
Точно ластовые)
Докер для дева подет

2022-08-05 12:46 UTC, Stilwuc commented on src/HackerNews/MainPage.tsx
> +    setNews(() => {
Уже писал, еще раз напишу
![image](https://user-images.githubusercontent.com/44724024/183043902-ebbc08ab-6b32-47ed-92c3-87e1af961e50.png)

2022-08-05 12:46 UTC, Stilwuc commented on src/HackerNews/NewsInfo.tsx
> +      refreshOnClick();
При авторевреше начинаются проблемы
![image](https://user-images.githubusercontent.com/44724024/183080060-ef85ffd5-77d8-4b3f-891d-c3bf4d0da308.png)

2022-08-05 12:46 UTC, Stilwuc commented on src/HackerNews/Comment.tsx
> +          {renderKidsComments()}
На f5 комменты сразу не рендерятся.
Только если нажму refreshComments
![image](https://user-images.githubusercontent.com/44724024/183078948-6df4bcfb-aff7-47fa-9ef9-b0edebacc8d6.png)
![image](https://user-images.githubusercontent.com/44724024/183079010-2fa1c73a-4daa-4e62-8a57-2a850e51742a.png)

2022-08-06 13:04 UTC, sayonara20xx commented
Поправил, тупые ошибки были
https://codesandbox.io/s/infallible-kapitsa-951ubv - codesandbox

2022-08-06 13:12 UTC, Stilwuc commented
Вот теперь шикарно все 👍 
@sayonara20xx Можно мержить

2022-08-06 14:21 UTC, merged